### ISSUE TITLE
iasl 20180927 crashing when compiling certain dsl

### ISSUE THREAD

**Issue by vit9696** [acpica/acpica#413]
The latest iasl 20180927 crashes on macOS due to double free when compiling this file: [problematic.zip](https://github.com/acpica/acpica/files/2429860/problematic.zip). This issue appears to be a regression, and does not happen with 20180810.

Here is a report with AddressSanitizer enabled showing the stacktrace of the crash and the allocation.

```
=================================================================
==1880==ERROR: AddressSanitizer: attempting free on address which was not malloc()-ed: 0x63100000b152 in thread T0
    #0 0x1103a010d in wrap_free (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x5710d)
    #1 0x10fd400b8 in OptBuildShortestPath aslopt.c:525
    #2 0x10fd3d10d in OptOptimizeNamePath aslopt.c
    #3 0x10fd9d0e8 in XfNamespaceLocateBegin aslxref.c:779
    #4 0x10fd93636 in TrWalkParseTree asltree.c:966
    #5 0x10fd9b3d8 in XfCrossReferenceNamespace aslxref.c:240
    #6 0x10fcf8729 in CmDoCompile aslcompile.c:378
    #7 0x10fd85d6c in AslDoOneFile aslstartup.c:561
    #8 0x10fd1e7dd in main aslmain.c:273
    #9 0x7fff7d561014 in start (libdyld.dylib:x86_64+0x1014)

0x63100000b152 is located 43346 bytes inside of 65544-byte region [0x631000000800,0x631000010808)
allocated by thread T0 here:
    #0 0x1103a0497 in wrap_calloc (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x57497)
    #1 0x10fcec8ce in UtLocalCalloc aslallocate.c:185
    #2 0x10fcf22e6 in UtLocalCacheCalloc aslcache.c:212
    #3 0x10fce31d6 in FlStrdup adfile.c:361
    #4 0x10fce300d in FlSplitInputPathname adfile.c:408
    #5 0x10fd85afe in AslDoOneFile aslstartup.c:447
    #6 0x10fd1e7dd in main aslmain.c:273
    #7 0x7fff7d561014 in start (libdyld.dylib:x86_64+0x1014)

SUMMARY: AddressSanitizer: bad-free (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x5710d) in wrap_free
==1880==ABORTING
Abort trap: 6
```

**Comment by roddy20** [comment]
[Pre-Edited DSDT.zip](https://github.com/acpica/acpica/files/2430882/Pre-Edited.DSDT.zip)
another file with the similar problem

**Comment by SchmErik** [comment]
This patch should fix the issue. Please give it a try

```
From cefaf78f1d57bf420299b48079b57c29d997fd71 Mon Sep 17 00:00:00 2001
From: Erik Schmauss <erik.schmauss@intel.com>
Date: Mon, 1 Oct 2018 14:02:49 -0700
Subject: [PATCH] iASL: do not free memory allocated from a local cache

This is unnecessary and causes a crash. Memory allocated from a cache
will be reclaimed after iASL terminates.

Signed-off-by: Erik Schmauss <erik.schmauss@intel.com>
---
 source/compiler/aslopt.c | 1 -
 1 file changed, 1 deletion(-)

diff --git a/source/compiler/aslopt.c b/source/compiler/aslopt.c
index 0b20e6033..51296ffef 100644
--- a/source/compiler/aslopt.c
+++ b/source/compiler/aslopt.c
@@ -522,7 +522,6 @@ OptBuildShortestPath (
 
 Cleanup:
 
-    ACPI_FREE (NewPathExternal);
     return (Status);
 }
 
-- 
2.17.1
```

**Comment by vit9696** [comment]
Works fine now, thank you. Shall I close the issue?
